### ISSUE TITLE
How to change `IMG_SIZE`?

### ISSUE THREAD

**Issue by samuelyutt** [CGCL-codes/AMT-GAN#8]
I have tried to change `IMG_SIZE` from 256 to 128 in `configs.yaml` since I have no enough GPU memory. However, I got the following error when running `python train.py` after changing.
```
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    train_net(config)
  File "train.py", line 17, in train_net
    solver.train()
  File "/media/ibm/D/yutt/AMT-GAN/backbone/solver.py", line 269, in train
    fake_A = self.G(image_s, image_r, mask_s, mask_r, dist_s, dist_r)
  File "/home/ibm/anaconda3/envs/AMT-GAN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/ibm/D/yutt/AMT-GAN/backbone/net.py", line 316, in forward
    weight = self.get_weight(mask_c, mask_s, c_tnet, s, diff_c, diff_s)
  File "/media/ibm/D/yutt/AMT-GAN/backbone/net.py", line 252, in get_weight
    fea_c = fea_c * mask_c_re  # (3, c, h, w) 3 stands for 3 parts
RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 3
```
I realized that the size of `fea_c` is related to `IMG_SIZE`. What is the correct way to modify `IMG_SIZE`? Or is there any other way to reduce CUDA memory?

**Comment by SheltonLiu-N** [comment]
Change backbone.net.get_weight function as follows:
```
def get_weight(self, mask_c, mask_s, fea_c, fea_s, diff_c, diff_s):
        HW = 32 * 32
        batch_size = 3
        assert fea_s is not None  # fea_s when i==3
        # get 3 part fea using mask
        channel_num = fea_s.shape[1]

        mask_c_re = F.interpolate(mask_c, size=32).repeat(1, channel_num, 1, 1)  # (3, c, h, w)
        diff_c = F.interpolate(diff_c, size=32)
        diff_s = F.interpolate(diff_s, size=32)
        fea_c = fea_c.repeat(3, 1, 1, 1)  # (3, c, h, w)
        fea_c = fea_c * mask_c_re  # (3, c, h, w) 3 stands for 3 parts

        mask_s_re = F.interpolate(mask_s, size=32).repeat(1, channel_num, 1, 1)
        fea_s = fea_s.repeat(3, 1, 1, 1)
        fea_s = fea_s * mask_s_re

        theta_input = torch.cat((fea_c * 0.01, diff_c), dim=1)
        phi_input = torch.cat((fea_s * 0.01, diff_s), dim=1)

        theta_target = theta_input.view(batch_size, -1, HW)  # (N, C+136, H*W)
        theta_target = theta_target.permute(0, 2, 1)  # (N, H*W, C+136)
        phi_source = phi_input.view(batch_size, -1, HW)  # (N, C+136, H*W)
        weight = torch.bmm(theta_target, phi_source)  # (3, HW, HW)
        with torch.no_grad():
            v = weight.detach().nonzero().long().permute(1, 0)
            # This clone is required to correctly release cuda memory.
            weight_ind = v.clone()
            del v
            torch.cuda.empty_cache()

        weight *= 200  # hyper parameters for visual feature
        weight = F.softmax(weight, dim=-1)
        weight = weight[weight_ind[0], weight_ind[1], weight_ind[2]]
        ret = torch.sparse.FloatTensor(weight_ind, weight, torch.Size([3, HW, HW]))
        return ret
```
It will work. ^ ^

**Comment by samuelyutt** [comment]
Very appreciate to your help! It worked! ^_^
